# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-26 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_auto_20170825_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportprovider',
            name='gb_per_sq_km_constant',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
